#!/bin/bash

SCRIPT_PATH=`dirname $0`

# it now starts with the session (see gnome-session-setup-lvillani/)
#unity-settings-daemon &

# http://off-topic.sardemff7.net/post/2012/06/21/About-the-GNOME-features-in-an-alternative-environment
gnome-terminal --role=xterm_scratchpad -e zsh &

# Note: for some reason the nm-applet icon is not showing now in the tray area, switch to wicd
#nm-applet &
wicd-client &
update-notifier &
volnoti &
~/deadbeef/deadbeef &

#setxkbmap us,ru -option "grp:caps_toggle,grp_led:scroll" -option compose:menu
$SCRIPT_PATH/keyboard-setup.sh

#cronfile=$SCRIPT_PATH/scripts/battery-info.cron.txt
#crontab -l | grep -v "battery-info.sh" | { cat; cat $cronfile; } | crontab -
