#!/bin/bash

SCRIPT_PATH=`dirname $0`

#xrandr --dpi 220
# xrandr --output DP-1-2-1 --scale 1.75x1.75 --dpi 220
# xrandr --output eDP-1-1 --dpi 220
# xrandr --output eDP-1-1 --scale 2.0x2.0

# Set dpi and scale for laptop screen
xrandr --output eDP-1 --dpi 216 --scale 1.2x1.2
#
# Check the current resolution:
# xdpyinfo | grep -B 2 resolution 
#
# How to calculate dpi: https://winaero.com/blog/find-change-screen-dpi-linux/
# $ xrandr | grep -w connected
#  eDP-1 connected primary 3744x2106+0+0 (normal left inverted right x axis y axis) 340mm x 190mm
#
# Physical size: 340mm x 190mm -> 13.39 in x 7.48 in
# DPI: 3744 / 13.39 = 279.6; 2106 / 7.48 = 281.6
# (but actual resolution in gnome-control-center is 2880 x 1620):
# DPI: 2880 / 13.39 = 215; 1620 / 7.48 = 216
#
# Related gnome settings:
#
# gsettings get org.gnome.desktop.interface text-scaling-factor
# gsettings set org.gnome.desktop.interface text-scaling-factor 1.0
#
# gsettings get org.gnome.desktop.interface scaling-factor
# gsettings set org.gnome.desktop.interface scaling-factor 1.0

# it now starts with the session (see gnome-session-setup-lvillani/)
# unity-settings-daemon &


/usr/lib/gnome-settings-daemon/gsd-xsettings &
# /usr/lib/gnome-settings-daemon/gsd-a11y-settings &
# /usr/lib/gnome-settings-daemon/gsd-backlight-helper &
# /usr/lib/gnome-settings-daemon/gsd-color &
# /usr/lib/gnome-settings-daemon/gsd-datetime &
# /usr/lib/gnome-settings-daemon/gsd-dummy &
# /usr/lib/gnome-settings-daemon/gsd-housekeeping &
# /usr/lib/gnome-settings-daemon/gsd-keyboard &
# /usr/lib/gnome-settings-daemon/gsd-media-keys &
# /usr/lib/gnome-settings-daemon/gsd-power &
# /usr/lib/gnome-settings-daemon/gsd-printer &
# /usr/lib/gnome-settings-daemon/gsd-print-notifications &
# /usr/lib/gnome-settings-daemon/gsd-rfkill &
# /usr/lib/gnome-settings-daemon/gsd-screensaver-proxy &
# /usr/lib/gnome-settings-daemon/gsd-sharing &
# /usr/lib/gnome-settings-daemon/gsd-smartcard &
# /usr/lib/gnome-settings-daemon/gsd-sound &
# /usr/lib/gnome-settings-daemon/gsd-wacom &
# /usr/lib/gnome-settings-daemon/gsd-wacom-led-helper &
# /usr/lib/gnome-settings-daemon/gsd-wacom-oled-helper &
# /usr/lib/gnome-settings-daemon/gsd-wacom-wwan &

# /usr/bin/gnome-software --gapplication-service
/usr/lib/gnome-disk-utility/gsd-disk-utility-notify &

# gnome-power-manager &
gnome-flashback &

# Note: to remove the bottom panel, run:
#     # check the list of pannels
#     gsettings get org.gnome.gnome-panel.layout toplevel-id-list
#     ['top-panel', 'bottom-panel']
#     # remove bottom panel
#     gsettings set org.gnome.gnome-panel.layout toplevel-id-list "['top-panel']"
# And to restore it, run
#     gsettings set org.gnome.gnome-panel.layout toplevel-id-list "['top-panel', 'bottom-panel']"
#
# In general, it makes sense whether to keep the bottom paned or i3status, so alternative is to 
# hide the i3status (just comment out bar {...} settings in the i3 config)
#
# gnome-panel is needed because with current session setup the nm-applet and some other icons are not
# shown in the i3status bar, the only workaround I found for now is to also run the gnome-panel
#
# There is also a shortcut to show/hide the top panel - $mod+p
# gnome-panel&

# http://off-topic.sardemff7.net/post/2012/06/21/About-the-GNOME-features-in-an-alternative-environment
gnome-terminal --role=xterm_scratchpad -e zsh &
# konsole --title=termscratch --hide-menubar --hide-tabbar -e zsh &
# uxterm -class UXTerm -title UXTermScratch -u8 "$@" -fa "Iosevka Medium:size=9" tmux

# Note: for some reason the nm-applet icon is not showing now in the tray area, switch to wicd
nm-applet &
#wicd-client &
update-notifier &
# volnoti &
# ~/deadbeef/deadbeef &

# http://127.0.0.1:8384/#
syncthing &

#setxkbmap us,ru -option "grp:caps_toggle,grp_led:scroll" -option compose:menu
$SCRIPT_PATH/keyboard-setup.sh

#cronfile=$SCRIPT_PATH/scripts/battery-info.cron.txt
#crontab -l | grep -v "battery-info.sh" | { cat; cat $cronfile; } | crontab -
